### ISSUE TITLE
try removing ssl hack

### ISSUE THREAD

**Issue by dhalperi** [uwdb/ascot_myria#24]
mirrored from #11 

Can you try removing the hack in c7e3e53 and see if it works? I re-generated the SSL certificates tonight and I may have fixed the problem.

(Needing to include the full chain of SSL certificates in the servers.)

**Comment by jortiz16** [comment]
Done. It works without that. Thanks!

**Comment by beame** [comment]
Hi Dan,

I am on a paper we submitted to PODS done using the DB github area.   
However, I don't need to get generic myria messages.  Is there a way I 
can stop getting them?

Thanks,

Paul

**Comment by domoritz** [comment]
@beame you should be able to go to the myria github page at https://github.com/uwescience/myria and change your status to not watching. 

![screen shot 2015-01-16 at 21 42 03](https://cloud.githubusercontent.com/assets/589034/5787846/9e917414-9dc8-11e4-8b1c-4368ee81d69d.png)
